# Generated by Django 5.0.1 on 2024-02-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='confirme_password',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
