# Generated by Django 5.0.1 on 2024-02-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAccount', '0002_myuser_confirme_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='confirme_password',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
