# Generated by Django 5.0.1 on 2024-02-06 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAswer', '0002_answeruserquiz'),
        ('AppQuiz', '0003_remove_quiz_level_quizcategory_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeruserquiz',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppQuiz.quiz'),
        ),
    ]
