# Generated by Django 5.0.1 on 2024-02-07 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAswer', '0003_answeruserquiz_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answeruserquiz',
            name='question',
        ),
    ]
