# Generated by Django 5.0.1 on 2024-02-07 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAswer', '0004_remove_answeruserquiz_question'),
        ('AppQuiz', '0003_remove_quiz_level_quizcategory_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeruserquiz',
            name='response_possible',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='AppAswer.answerquiz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answeruserquiz',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppQuiz.quiz'),
        ),
    ]
