# Generated by Django 5.0.1 on 2024-02-06 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppQuiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='catgory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='AppQuiz.quizcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='Level',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='AppQuiz.levelquiz'),
            preserve_default=False,
        ),
    ]
