# Generated by Django 5.0.1 on 2024-02-06 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppQuiz', '0002_levelquiz_quiz_catgory_quiz_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='Level',
        ),
        migrations.AddField(
            model_name='quizcategory',
            name='Level',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='AppQuiz.levelquiz'),
            preserve_default=False,
        ),
    ]
