# Generated by Django 5.0.1 on 2024-02-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppQuiz', '0004_quiz_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
